language: python

sudo: required

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-django1.9-drf3.3

matrix:
    fast_finish: true

before_install:
    - wget https://github.com/centrifugal/centrifugo/releases/download/v1.3.3/centrifugo-1.3.3-linux-amd64.zip
    - unzip centrifugo-1.3.3-linux-amd64.zip
    - sudo mv centrifugo-1.3.3-linux-amd64/centrifugo /usr/bin/centrifugo
    - mv /home/travis/build/raphaelgyory/django-rest-messaging-js/webpack-stats-example-travis.json /home/travis/build/raphaelgyory/django-rest-messaging-js/webpack-stats-example.json

install:
    - pip install tox
    - npm install

script:
    - tox -e $TOX_ENV
