language: python

sudo: required

matrix:
  fast_finish: true

before_install:
    - wget https://github.com/centrifugal/centrifugo/releases/download/v1.3.3/centrifugo-1.3.3-linux-amd64.zip
    - unzip centrifugo-1.3.3-linux-amd64.zip
    - sudo mv centrifugo-1.3.3-linux-amd64/centrifugo /usr/bin/centrifugo
    - sudo chmod +x runtests.py

install:
    - pip install -r requirements.txt
    - npm install

before_script:
    - echo "{"status":"done","chunks":{"main":[{"name":"example-django-rest-messaging-1.0.1.js","path":"/home/travis/build/raphaelgyory/django-rest-messaging-js/example/dist/example-django-rest-messaging-1.0.1.js"}]}}" >> /home/travis/build/raphaelgyory/django-rest-messaging-js/webpack-stats-example.json
    - python migrate.py
    
script:
    - ./runtests.py


